name: SecureDiary CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd SecureDiary

            git pull origin main

            sudo docker stop securediary || true
            sudo docker rm securediary || true

            sudo docker build -t securediary .

            sudo docker run -d -p 5000:5000 --name securediary securediary